### ISSUE TITLE
Erroneous String Compare

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/flogger#101]
https://github.com/google/flogger/blob/477d892868ac62ff8d762f732be3ba61cf7204ec/api/src/main/java/com/google/common/flogger/LogContext.java#L563
Strings should be compared with the equals() method, not == or !=.

**Comment by kluever** [comment]
See the comment directly before that line:

>     // Using "!=" is fast and sufficient here because the only real case this should be skipping
>    // is when we called log(String) or log(), which should not result in a template being created.
>    // DO NOT replace this with a string instance which can be interned, or use equals() here,
>    // since that could mistakenly treat other calls to log(String, Object...) incorrectly.
