### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/flogger#102]
https://github.com/google/flogger/blob/477d892868ac62ff8d762f732be3ba61cf7204ec/api/src/main/java/com/google/common/flogger/backend/Platform.java#L40
This field is never used.

**Comment by kluever** [comment]
It is used internally, but yes, I suppose we could strip that `String` if we really wanted to.

**Comment by kluever** [comment]
Fixed internally...will be mirrored out shortly.
