### ISSUE TITLE
How to add custom logger back-end?

### ISSUE THREAD

**Issue by cslee00** [google/flogger#13]
It looks like PlatformProvider may be the mechanism for this, though it could be argued it's responsibility is deciding between Android or 'Default' platforms.

Adding a JAR with a custom PlatformProvider does not work (in all cases) as PlatformProvider is included in the base flogger JAR (it may work if at the right spot in the classpath - quirky, not to be relied on).

**Comment by ronshapiro** [comment]
This currently isn't supported but we're adding support for this. See #12 for some discussion.
