### ISSUE TITLE
Incorrect pattern layout behaviour when using log4j2 backend

### ISSUE THREAD

**Issue by StefanHirche** [google/flogger#143]
I just tried to use flogger as our main logging framework with log4j2 backend. I tried different layout patterns and want to share some behaviour issues.
The Pattern looks like this:
`%X{loginId}/%X{loginName} - %d{ISO8601} [%c{10} - %l/%F] %t %-5level:%msg%n`
I use
`ThreadContext.put("loginId", "DDU");
ThreadContext.put("loginName", "Donald Duck");`
to add values to the context.

Log4J2 outputs `DDU/Donald Duck - 2020-03-24T21:18:06,554 [class standalone.Printer - standalone.Printer.print(Printer.java:19)/Printer.java] main ERROR:Logger error`
Flogger outputs `/ - 2020-03-24T21:18:06,552 [standalone.Printer:DEBUG in c387f44 - /] main ERROR:Flogger error`

**Comment by hagbard** [comment]
This was contributed backend, so I'm afraid you'll need to contact the original author: https://github.com/paladox

**Comment by nglorioso** [comment]
@paladox

**Comment by paladox** [comment]
This should be fixed with https://github.com/google/flogger/pull/154

**Comment by paladox** [comment]
Even if  #154 does not fix this issue, it's still needed.

**Comment by StefanHirche** [comment]
The line number issue is still there.
