### ISSUE TITLE
`UNUSED LOG ARGUMENTS` even when format string contains no placeholders and varargs are empty

### ISSUE THREAD

**Issue by dpursehouse** [google/flogger#158]
If I have a wrapper method that invokes flogger, i.e. something like this:

```
void doLog(FluentLogger logger, String format, Object... args) {
     logger.atSevere().log(format, args);

     // do other stuff in addition to only logging via flogger
     ...
     ...
}
```

This is fine:

```
doLog(myLogger, "Foo %s", foo);
```

but this causes the `UNUSED LOG ARGUMENTS` to be logged:

```
doLog(myLogger, "Bar")
```

I suppose one could argue that this is not really how flogger was intended to be used, but would it be possible to only emit that warning if `args` is not empty?

**Comment by hagbard** [comment]
You should use the "logVarargs()" method, that's exactly what it's for.

**Comment by dpursehouse** [comment]
🤦

Thanks.  That does indeed fix it.  Sorry for the noise.
