### ISSUE TITLE
Was the flogger name intentional?

### ISSUE THREAD

**Issue by crockpotveggies** [google/flogger#17]
Thought I'd bring this to your attention, but flogger is not an original word. I don't think it was intentional, but I remembered seeing the word used in exchange with "drawing and quartering" which is the act of corporal punishment. When I looked up the definition of "flogger" it raised an eyebrow.

See [flagellation](https://en.wikipedia.org/wiki/Flagellation) and the urban dictionary for [flogger](https://www.urbandictionary.com/define.php?term=flogger&utm_source=search-action). Note the definition may be NSFW.

I think it was just meant to be a combination of "fluent + logger" and the result was unintended. Anyways, feel free to close this.

**Comment by jbduncan** [comment]
Wow... I personally knew of the link between flogging and flagellation (considering just this, I thought that the pun behind this project's name was innocent enough to not raise _too_ many eyebrows), but I didn't actually realise that the word "flogger" has a NSFW meaning...

@ronshapiro WDYT about this? I personally think it's worth renaming the project to "fluent-logger" or something else.

**Comment by kevinb9n** [comment]
We decided to name the library Flogger.

**Comment by jbduncan** [comment]
Fair enough! :)
