### ISSUE TITLE
Add Flogger to cs.opensource.google

### ISSUE THREAD

**Issue by CydeWeys** [google/flogger#193]
It'd be great if Flogger were on https://cs.opensource.google/ (basically externally accessible Code Search) for easy codebase perusal and cross-referencing with other projects that use it. Most of Google's most important open source projects are already on there including Abseil, Angular, Bazel, Copybara, Dart, Fuchsia, Go, Guava, TensorFlow, etc., so it'd be awesome to include Truth as well. See http://go/osscs-onboarding for instructions.

Truth is currently working on this as well ([see here](https://github.com/google/truth/issues/769)), and apart from having to come up with a placeholder logo it's looking really easy.

**Comment by kluever** [comment]
Fixed
