### ISSUE TITLE
Add more features :)

### ISSUE THREAD

**Issue by yupitomets** [google/flogger#2]
Let me be a creator of the first issue of this project with high potential.

**Comment by ronshapiro** [comment]
I'm going to assume you wanted to be cute and get the first issue (in which case, great job! though, the devil's advocate in me hates to mention that #1 did get in before this...)

But in all honesty, please only create an issue if you actually have a suggestion or a bug. This is library is very mature (almost 3/4 of all of Google's Java uses Flogger) so we're not going to add features for the sake of having features.

**Comment by yuriipitomets** [comment]
3/4 of all Google's java projects use Flogger? aha, what a funny joke

**Comment by jbduncan** [comment]
@yuriipitomets I don't think @ronshapiro's content was meant to be a joke. :)
