### ISSUE TITLE
CallerFinder should use StackWalker API

### ISSUE THREAD

**Issue by marschall** [google/flogger#30]
CallerFinder should use the [StackWalker API](https://docs.oracle.com/javase/9/docs/api/java/lang/StackWalker.html) when available (Java 9+) to avoid the exception. This can easily be solved with [Multi-Release JAR Files](http://openjdk.java.net/jeps/238) which are available on Java 9+.

**Comment by hagbard** [comment]
Flogger's core library supports all the way back to Java 6, so cannot (yet) take advantage of these nice new classes. When it can, I'll definitely switch.

**Comment by marschall** [comment]
There are still ways to use it when running on Java 9+. Either through [Multi-Release JAR Files](http://openjdk.java.net/jeps/238) or through reflection.
