### ISSUE TITLE
@CheckReturnValue on methods

### ISSUE THREAD

**Issue by thekeenant** [google/flogger#35]
![image](https://user-images.githubusercontent.com/1189775/43616536-add1b63a-9682-11e8-89dc-bb3cc3f82359.png)

This notification from IntelliJ leads me to think the `LoggingApi` methods themselves should be annotated with `@CheckReturnValue` instead of the `LoggingApi` class. But I would think IntelliJ/Android Studio should be smart enough to know a `void` method has no return value and that it should not warn in that case.

**Comment by ronshapiro** [comment]
Not much we can do here - maybe a good bug to be filing for IntelliJ?
