### ISSUE TITLE
Default JavaDocs generated for Flogger confusingly suggest it's deprecated (it isn't).

### ISSUE THREAD

**Issue by hagbard** [google/flogger#354]
I assume this isn't what people would want to see in the JavaDocs for Flogger.

![image](https://github.com/google/flogger/assets/867170/27937782-d894-4e30-abd5-d9e3974385f0)

I generated this in IntelliJ via the normal "Generate JavaDoc" flow with the extra parameters:

```
-Xdoclint:none --ignore-source-errors
```

which I needed because Bazel doesn't set up classpaths for JavaDoc generation, and trying to build the `//tools:all_javadoc` target on Windows fails.

I don't actually know why this is saying such incorrect things about deprecation, but I imagine that an entry in each package-info.java file (JavaDoc comment *above* the package declaration) might help things.

I'm happy to provide the text for the package descriptions, but the main thing is not having the JavaDoc output claim that everything is deprecated.

**Comment by cgdecker** [comment]
That is pretty strange. The Javadoc built by `//tools:all_javadoc` doesn't seem to have that problem at least, and I can't really imagine where anything would be getting deprecated from.

**Comment by hagbard** [comment]
I'm happy to close this. I've since made enough changes locally that I cannot reproduce it and the official JavaDoc doesn't suffer from it. No idea what was going on here.
