### ISSUE TITLE
Error: 'JavaInfo' value has no field or method 'transitive_deps'

### ISSUE THREAD

**Issue by sgowroji** [google/flogger#361]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3289#018a6841-485b-4870-9b24-b31ba0ed35d1

Logs:
```
 ERROR: /var/lib/buildkite-agent/builds/bk-docker-tbrp/bazel-downstream-projects/flogger/api/BUILD:142:16: in javadoc_library rule //api:api_javadoc:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/46f6932227dc0e2385dd390c86abe0e8/external/google_bazel_common/tools/javadoc/javadoc.bzl", line 29, column 49, in _javadoc_library
		transitive_deps.append(dep[JavaInfo].transitive_deps)
Error: 'JavaInfo' value has no field or method 'transitive_deps'
Available attributes: _compile_time_java_dependencies, _constraints, _neverlink, _transitive_full_compile_time_jars, annotation_processing, api_generating_plugins, compilation_info, compile_jars, full_compile_jars, java_outputs, module_flags_info, outputs, plugins, runtime_output_jars, source_jars, transitive_compile_time_jars, transitive_native_libraries, transitive_runtime_jars, transitive_source_jars
(02:10:59) ERROR: /var/lib/buildkite-agent/builds/bk-docker-tbrp/bazel-downstream-projects/flogger/api/BUILD:142:16: Analysis of target '//api:api_javadoc' failed
(02:10:59) ERROR: Analysis of target '//api:api_javadoc' failed; build aborted

```
Culprit : https://github.com/bazelbuild/bazel/commit/72058be0628e84741232cb116a7199eb92638f84

CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Hi @eamonnmcmanus, We are still seeing this error in the latest CI https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3301#018a8793-2c13-4b0b-a5a9-7b36a0934230

**Comment by cpovirk** [comment]
(I would imagine it's now just a matter of updating the bazel-common version in Flogger (like [this previous upgrade](https://github.com/google/flogger/commit/5fbd8220c0d7788936d5613d637b15e58b47e487)).)

**Comment by eamonnmcmanus** [comment]
> (I would imagine it's now just a matter of updating the bazel-common version in Flogger (like [this previous upgrade](https://github.com/google/flogger/commit/5fbd8220c0d7788936d5613d637b15e58b47e487)).)

Yes, I was in the process of doing that. Though mysteriously I wasn't able to reproduce the build failure in a local clone of this repo.

**Comment by cpovirk** [comment]
OK, cool, just wanted to make sure you weren't banging your head against anything... or, apparently, at least not against the thing that I'd thought :)

IIUC, Bazel has a system by which they compile tons of projects with a near-head build of Bazel and/or with various incompatible-change flags enabled. Then they report problems that projects would see in the near future but don't actually see yet with normal builds.

**Comment by sgowroji** [comment]
https://github.com/google/flogger/issues/364 We are still seeing this error.
