### ISSUE TITLE
Consider excluding Guava dependency from log4j backend

### ISSUE THREAD

**Issue by ineuwirth** [google/flogger#44]
Currently `flogger-log4j-backend:jar:0.3.1` depends on `guava:jar:25.0-jre`.

Please consider removing the dependency because:
 - Many projects already depend on some Guava version and they might end up with some kind of conflict using flogger.
 - Having Guava adds ~2.6M to the build result.
 - As of now (latest commit in the public flogger repository is cd769d1a738125fdd4c1bfd2258c6f68ddef77de) only `ImmutableMap` is being used from Guava (apart from the unit tests).

I am wondering what are the good arguments for the other point of view. If this dependency can and should be removed, I am happy to provide a pull request.

**Comment by hagbard** [comment]
Yes, we should do this. Backends should generally be free from external dependencies in the same way that the core library is (other than the logging library they interface with, obviously).
