### ISSUE TITLE
Bobbin backend support

### ISSUE THREAD

**Issue by apryamostanov** [google/flogger#75]
Dear Team,

Please take a look at Bobbin logger: https://github.com/INFINITE-TECHNOLOGY/BOBBIN

Can you consider to adapt it as one of supported Flogger backends?

It features high performance and effective configuration.

Currently there are no known issues in Bobbin, it is a stable release.

If needed we can do appropriate changes (if any) in Bobbin.

Philosophically our vision is very close to that of Flogger, e.g. passing Objects to logger rather than Strings, etc.

Thank you.

**Comment by hagbard** [comment]
As Bobbin appears to be a somewhat experimental and not widely used logger, I'm afraid we can't justify spending the resources to maintain a backend for it as part of the standard Flogger project.

Sorry, but there's only so much of my 20% time to go around. I do want Flogger to work with many backends though, so I will consider any ideas for modifications that make that easier very carefully.

**Comment by apryamostanov** [comment]
Thank you for the feedback, that’s fair. 
Let’s come back to it after Bobbin becomes more acknowledged. 

Keep up the great work!
